name: Flutter One-Time Build

on:
  workflow_dispatch:

jobs:
  run-flutter-one-time-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "one-time"
